name = "noxbot"
main = "./src/server.js"
compatibility_date = "2024-09-23"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[durable_objects.bindings]]
name = "NOXBOT_DATA"
class_name = "UserData"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["UserData"] # Array of new classes