name = "noxbot"
main = "./src/server.js"
compatibility_date = "2024-09-23"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "noxbotdata"
id = "5b30a3eedbb24bd1b9dee809ca012426"